name: Test MoviePy Import

on: [push]

jobs:
  test-moviepy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install moviepy

      - name: Verify MoviePy
        run: |
          python -c "import moviepy; print('✅ MoviePy version:', moviepy.__version__)"
          python -c "from moviepy.editor import VideoFileClip; print('✅ moviepy.editor import works!')"
