name: Test MoviePy with Video

on: [push, pull_request]

jobs:
  test-moviepy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install moviepy

      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Generate test video
        run: |
          python - <<'PYCODE'
          from moviepy.editor import TextClip, CompositeVideoClip
          # نص متحرك يظهر على خلفية سوداء
          clip = TextClip("Hello GitHub Actions", fontsize=70, color="white", size=(640, 360))
          clip = clip.set_duration(5).set_position("center")
          final = CompositeVideoClip([clip])
          final.write_videofile("output.mp4", fps=24)
          PYCODE

      - name: Upload video artifact
        uses: actions/upload-artifact@v4
        with:
          name: moviepy-test-video
          path: output.mp4
